section-2-make-web-applications-with-python-using-django-3.2/photo-project/photo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photo/', include('photoapp.urls')),
]

section-2-make-web-applications-with-python-using-django-3.2/photo-project/photoapp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:photo_id>/', views.detail, name='detail'),
]

section-2-make-web-applications-with-python-using-django-3.2/photo-project/photoapp/models.py
from django.db import models
# Create your models here.
from django.db.models import CharField


class Photo(models.Model):
    name = models.CharField(max_length=100)
    creator: CharField = models.CharField(max_length=100)
    price = models.CharField(max_length=100)

    def __str__(self):
        return self.name + '-' + self.creator

section-2-make-web-applications-with-python-using-django-3.2/photo-project/photoapp/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from .models import Photo
from django.template import loader
from django.shortcuts import render
from django.http import Http404


# Create your views here.


def index(request):
    all_photo = Photo.objects.all()
    context = {
        'all_photo': all_photo
    }
    return render(request, 'photoapp/index.html', context)


def detail(request, photo_id):
    all_photo = Photo.objects.get(id= photo_id)
    context = {
        'photo' : all_photo
    }
    return render(request, 'photoapp/detail.html', context)

section-2-make-web-applications-with-python-using-django-3.2/photo-project/photoapp/templates/photoapp/detail.html
    <h1>{{photo.id}}</h1>
    <h1>{{photo.name}}</h1>
    <h1>{{photo.creator}}</h1>
    <h1>{{photo.price}}</h1>

section-2-make-web-applications-with-python-using-django-3.2/photo-project/photoapp/templates/photoapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'photoapp/style.css' %}" >
</head>
<body>
    <h1>Khoa</h1>
    <ul>
        {% for photo in all_photo %}
        <li>
            <a href ="{% url 'photo:detail' photo.id %}">{{photo.name}}</a>
        </li>
        {%endfor%}
    </ul>
</body>
</html>